name: 'dataiq'
version: '1.0.0'

profile: 'dataiq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dataiq:
    raw:
      +materialized: table
    staging:
      +materialized: table
    marts:
      +materialized: table
